import * as Joi from 'joi';
export declare const Alarm_CreateJoi: {
    '@baseType': Joi.StringSchema;
    '@schemaLocation': Joi.StringSchema;
    '@type': Joi.StringSchema;
    ackState: Joi.StringSchema;
    ackSystemId: Joi.StringSchema;
    ackUserId: Joi.StringSchema;
    affectedService: Joi.ArraySchema;
    alarmChangedTime: Joi.DateSchema;
    alarmClearedTime: Joi.DateSchema;
    alarmDetails: Joi.StringSchema;
    alarmEscalation: Joi.BooleanSchema;
    alarmRaisedTime: Joi.DateSchema;
    alarmReportingTime: Joi.DateSchema;
    alarmType: Joi.StringSchema;
    alarmedObject: Joi.ObjectSchema<any>;
    alarmedObjectType: Joi.StringSchema;
    clearSystemId: Joi.StringSchema;
    clearUserId: Joi.StringSchema;
    comment: Joi.ArraySchema;
    correlatedAlarm: Joi.ArraySchema;
    crossedThresholdInformation: Joi.ObjectSchema<any>;
    externalAlarmId: Joi.StringSchema;
    isRootCause: Joi.BooleanSchema;
    parentAlarm: Joi.ArraySchema;
    perceivedSeverity: Joi.StringSchema;
    place: Joi.ArraySchema;
    plannedOutageIndicator: Joi.StringSchema;
    probableCause: Joi.StringSchema;
    proposedRepairedActions: Joi.StringSchema;
    reportingSystemId: Joi.StringSchema;
    serviceAffecting: Joi.BooleanSchema;
    sourceSystemId: Joi.StringSchema;
    specificProblem: Joi.StringSchema;
    state: Joi.StringSchema;
};
