import * as Joi from 'joi';
export declare const ProductOfferingQualification_UpdateJoi: {
    '@baseType': Joi.StringSchema;
    '@schemaLocation': Joi.StringSchema;
    '@type': Joi.StringSchema;
    category: Joi.ObjectSchema<any>;
    channel: Joi.ObjectSchema<any>;
    description: Joi.StringSchema;
    effectiveQualificationDate: Joi.DateSchema;
    expectedPOQCompletionDate: Joi.DateSchema;
    expirationDate: Joi.DateSchema;
    instantSyncQualification: Joi.BooleanSchema;
    note: Joi.ArraySchema;
    place: Joi.ArraySchema;
    productOfferingQualificationItem: Joi.ArraySchema;
    provideAlternative: Joi.BooleanSchema;
    provideOnlyAvailable: Joi.BooleanSchema;
    provideUnavailabilityReason: Joi.BooleanSchema;
    qualificationResult: Joi.StringSchema;
    relatedParty: Joi.ArraySchema;
    requestedPOQCompletionDate: Joi.DateSchema;
    state: Joi.StringSchema;
};
