import * as Joi from 'joi';
export declare const ProductJoi: {
    '@baseType': Joi.StringSchema;
    '@schemaLocation': Joi.StringSchema;
    '@type': Joi.StringSchema;
    agreement: Joi.ArraySchema;
    billingAccount: Joi.ObjectSchema<any>;
    description: Joi.StringSchema;
    href: Joi.StringSchema;
    id: Joi.StringSchema;
    isBundle: Joi.BooleanSchema;
    isCustomerVisible: Joi.BooleanSchema;
    name: Joi.StringSchema;
    orderDate: Joi.DateSchema;
    place: Joi.ArraySchema;
    product: Joi.ArraySchema;
    productCharacteristic: Joi.ArraySchema;
    productOffering: Joi.ObjectSchema<any>;
    productOrderItem: Joi.ArraySchema;
    productPrice: Joi.ArraySchema;
    productRelationship: Joi.ArraySchema;
    productSerialNumber: Joi.StringSchema;
    productSpecification: Joi.ObjectSchema<any>;
    productTerm: Joi.ArraySchema;
    realizingResource: Joi.ArraySchema;
    realizingService: Joi.ArraySchema;
    relatedParty: Joi.ArraySchema;
    startDate: Joi.DateSchema;
    status: Joi.StringSchema;
    terminationDate: Joi.DateSchema;
};
