import * as Joi from 'joi';
export declare const ProductOffering_UpdateJoi: {
    '@schemaLocation': Joi.StringSchema;
    agreement: Joi.ArraySchema;
    attachment: Joi.ArraySchema;
    bundledProductOffering: Joi.ArraySchema;
    category: Joi.ArraySchema;
    channel: Joi.ArraySchema;
    description: Joi.StringSchema;
    isBundle: Joi.BooleanSchema;
    isSelective: Joi.BooleanSchema;
    isSellable: Joi.BooleanSchema;
    lifecycleStatus: Joi.StringSchema;
    lineOfBusiness: Joi.ObjectSchema<any>;
    marketSegment: Joi.ArraySchema;
    name: Joi.StringSchema;
    offerType: Joi.StringSchema;
    place: Joi.ArraySchema;
    prodSpecCharValueUse: Joi.ArraySchema;
    productOfferingCharacteristic: Joi.ArraySchema;
    productOfferingPrice: Joi.ArraySchema;
    productOfferingRelationship: Joi.ArraySchema;
    productOfferingTerm: Joi.ArraySchema;
    productSpecification: Joi.ObjectSchema<any>;
    resourceCandidate: Joi.ObjectSchema<any>;
    selectiveness: Joi.ObjectSchema<any>;
    serviceCandidate: Joi.ObjectSchema<any>;
    serviceLevelAgreement: Joi.ObjectSchema<any>;
    statusReason: Joi.StringSchema;
    validFor: Joi.ObjectSchema<any>;
    version: Joi.NumberSchema;
};
