import * as Joi from 'joi';
export declare const ServiceJoi: {
    '@baseType': Joi.StringSchema;
    '@schemaLocation': Joi.StringSchema;
    '@type': Joi.StringSchema;
    category: Joi.StringSchema;
    description: Joi.StringSchema;
    endDate: Joi.DateSchema;
    feature: Joi.ArraySchema;
    hasStarted: Joi.BooleanSchema;
    href: Joi.StringSchema;
    id: Joi.StringSchema;
    isBundle: Joi.BooleanSchema;
    isServiceEnabled: Joi.BooleanSchema;
    isStateful: Joi.BooleanSchema;
    name: Joi.StringSchema;
    note: Joi.ArraySchema;
    place: Joi.ArraySchema;
    relatedEntity: Joi.ArraySchema;
    relatedParty: Joi.ArraySchema;
    serviceCharacteristic: Joi.ArraySchema;
    serviceDate: Joi.StringSchema;
    serviceOrderItem: Joi.ArraySchema;
    serviceRelationship: Joi.ArraySchema;
    serviceSpecification: Joi.ObjectSchema<any>;
    serviceType: Joi.StringSchema;
    startDate: Joi.DateSchema;
    startMode: Joi.StringSchema;
    state: Joi.StringSchema;
    supportingResource: Joi.ArraySchema;
    supportingService: Joi.ArraySchema;
};
